baseURL: 'https://humantorch.github.io/'
languageCode: en-us
title: scott kosman
theme: PaperMod

markup:
  goldmark:
    renderer:
      unsafe: true


params:
  defaultTheme: light
  disableThemeToggle: false
  profileMode:
    enabled: true
    title: "scott kosman" # optional default will be site title
    subtitle: "Est. 1976. Engineering Leader and possible Fictional Character.<br><code><b>$ npx humantorch</b></code>"
    imageUrl: "scott-2.jpg" # optional
    # imageTitle: "<title of image as alt>" # optional
    imageWidth: 250 # custom size
    imageHeight: 250 # custom size
    # buttons:
    #   - name: "twitter"
    #     url: "https://twitter.com/humantorch"
    #   - name: "instagram"
    #     url: "https://instagram.com/humantorch"
  socialIcons: # optional
    - name: "twitter"
      url: "https://twitter.com/humantorch"
    - name: "instagram"
      url: "https://instagram.com/humantorch"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/scottkosman/"
    - name: "github"
      url: "https://github.com/humantorch/"
    - name: "CV"
      url: "skosman_resume2022.pdf"
    - name: "Email"
      url: "mailto:kosman.scott@gmail.com"
  params:
    assets:
      favicon: "favicon/favicon.png"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: readme
      name: Manager README
      url: /post/readme/
      weight: 10
    - identifier: journey
      name: Journey
      url: /post/journey/
      weight: 20
    - identifier: about
      name: About
      url: /post/about
      weight: 5