baseURL: 'https://scottkosman.com/'
languageCode: en-us
title: scott kosman
theme: PaperMod

markup:
  goldmark:
    renderer:
      unsafe: true


params:
  defaultTheme: light
  disableThemeToggle: false
  profileMode:
    enabled: true
    title: "scott kosman" # optional default will be site title
    subtitle: "Est. 1976. Engineering Manager, MSP Program at <a href=\"https://1password.com\">1Password</a>.<br><code><b>$ npx scottkosman</b></code>"
    imageUrl: "scott-2.jpg" # optional
    # imageTitle: "<title of image as alt>" # optional
    imageWidth: 250 # custom size
    imageHeight: 250 # custom size
  socialIcons: # optional
    - name: "instagram"
      url: "https://instagram.com/humantorch"
      align: center
    - name: "linkedin"
      url: "https://www.linkedin.com/in/scottkosman/"
      align: center
    - name: "github"
      url: "https://github.com/humantorch/"
      align: center
    - name: "CV"
      url: "https://docs.google.com/document/d/1gcEzsNHWAllGH9mt6bfjie900B-rQNiatwdHiRj_Yog/edit?usp=sharing"
      align: center
    - name: "Email"
      url: "mailto:kosman.scott@gmail.com"
      align: center
  assets:
    favicon: "favicon/favicon.png"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /post/about
      weight: 5
    - identifier: blog
      name: Thoughts
      url: /post/blog/
      weight: 8
    - identifier: readme
      name: Manager README
      url: /post/readme/
      weight: 10
    - identifier: journey
      name: Journey
      url: /post/journey/
      weight: 20